import _ from 'lodash'
class QuestionProviderAgent {
    static get $inject(){ return ['StateManagerAgent']};
    stateAgent = {};
    constructor(stateManagerAgent){
        this.stateAgent = stateManagerAgent;
    };
    getQuestions(){
        var resultingQuestions = [];

        //TODO: Retirar quando vierem as perguntas
        resultingQuestions = _.take(_.shuffle(_questions), 10);
        return angular.copy(resultingQuestions);

        if(this.stateAgent.isLeveling)
            resultingQuestions = this.getLevelingQuestions();
        const questions = _.shuffle(_questions);
        resultingQuestions = _.take(questions.filter(q => q.level == this.stateAgent.currentLevel), 10);
        return angular.copy(resultingQuestions);
    }
    getLevelingQuestions(){
        const questions = _.shuffle(_questions);
        const lv1 = _.take(questions.filter(q => q.level == 1), 2);
        const lv2 = _.take(questions.filter(q => q.level == 2), 2);
        const lv3 = _.take(questions.filter(q => q.level == 3), 2);
        const lv4 = _.take(questions.filter(q => q.level == 4), 2);
        const lv5 = _.take(questions.filter(q => q.level == 5), 2);
        return [...lv1,...lv2,...lv3,...lv4,...lv5]
    }
}

export default () => angular.module('med-edu').service('QuestionProviderAgent', QuestionProviderAgent)
  
  
const _questions = [
    {
        "level": 1,
        "question": "Quais os possíveis sintomas da miopia?",
        "option1": "Dor de cabeça, irritação ocular e lacrimejamento.",
        "option2": "Dor de cabeça, irritação auricular e cansaço.",
        "option3": "Irritação ocular, dor de cabeça e cansaço.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/McPPZBlg6OQ?start=82",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Além da má digestão, qual pode ser o motivo causador da azia?",
        "option1": "O hábito de fumar pode lesionar as células do esôfago causando dor.",
        "option2": "O retorno do suco gástrico para o esôfago, que por ser ácido acaba lesionando as células do esôfago e causando dor.",
        "option3": "Todas as respostas acima.",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "A azia pode ser causada por fatores como má digestão dos alimentos, excesso de peso, gravidez e ter o hábito de fumar. O principal sintoma de azia é a sensação de queimação que inicia no final do osso esterno, que está entre as costelas, e que vai até a garganta. Fonte: https://www.tuasaude.com/causas-da-azia/",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Quais os primeiros socorros se alguém está tendo um Acidente Vascular Cerebral - AVC?",
        "option1": "Verificar a respiração do indivíduo, colocando-o de barriga para cima e caso não respire iniciar a massagem cardíaca.",
        "option2": "Chamar a ambulância, verificar a respiração do indivíduo e após garantir a respiração colocá-lo de lado para aguardar o socorro.",
        "option3": "Chamar a ambulância, verificar a respiração do indivíduo, colocando-o de barriga para cima e caso não respire iniciar a massagem cardíaca.",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Os primeiros socorros para AVC podem evitar sequelas graves, como ficar paralisado ou não falar e, em alguns casos, podem permanecer para toda a vida, diminuindo a qualidade de vida do paciente. Por isso, por isso, é importante socorrer o individuo que está tendo um AVC o mais rápido possível para evitar sequelas. Fonte: https://www.tuasaude.com/primeiros-socorros-para-avc/",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Uma pessoa está com crise hipertensiva se...",
        "option1": "Sua pressão arterial está abaixo de 12x8.",
        "option2": "Sua pressçao arterial está acima de 12x8.",
        "option3": "Sua pressão arterial está acima de 12x18.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/1HDSpB_nYxs",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Por que a insulina é importante?",
        "option1": "Diminui a quantidade de glicose nas células.",
        "option2": "Permite que a glicose entre na corrente sanguínea.",
        "option3": "Permite que a glicose entre nas células.",
        "correct": "3",
        "explanationVideo": "https://www.youtube.com/embed/vAUbt17h6Co",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "O que é tuberculose?",
        "option1": "Uma doença bacteriana que ataca os pulmões.",
        "option2": "Uma doença viral que ataca os pulmões.",
        "option3": "Uma doença genética que ataca os pulmões.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/F0UVtuoTAGI",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Como surge o câncer?",
        "option1": "O câncer surge por um vírus que altera o DNA da célula, que passa a receber instruções erradas para sua ações.",
        "option2": "O câncer surge por uma mutação genética que altera o DNA da célula, que passa a receber instruções erradas para sua atividades.",
        "option3": "O câncer surge por uma mutação genética que altera mata as células e pode atingir todo o corpo, causando a morte do paciente.",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "O câncer surge a partir de uma mutação genética, ou seja, de uma alteração no DNA da célula, que passa a receber instruções erradas para as suas atividades. As alterações podem ocorrer em genes especiais, denominados proto-oncogenes, que a princípio são inativos em células normais. Quando ativados, os proto-oncogenes tornam-se oncogenes, responsáveis por transformar as células normais em células cancerosas. Fonte: https://www.inca.gov.br/como-surge-o-cancer",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Qual é a relação entre a fibrilação atrial e AVC?",
        "option1": "O AVC pode causar a fibrilação atrial.",
        "option2": "A fibrilação atrial pode causar o AVC.",
        "option3": "Nenhuma das respostas anteriores.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/jQgj_pcXtLg",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Quando ocorre a biodisponibilidade do álcool?",
        "option1": "Quando o álcool permanece no sangue por mais tempo do que o esperado porque as células não o absorvem.",
        "option2": "Quando o álcool permanece nas células por mais tempo porque foi absorvido rápido demais.",
        "option3": "Quando o álcool fica exposto no cérebro por mais tempo porque a quantidade ingerida foi alta demais.",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "alcool.jpg",
    },
    {
        "level": 1,
        "question": "Quais são as causas da embolia pulmonar?",
        "option1": "Cirurgias extensas, câncer, gravidez, obesidade e traumas.",
        "option2": "Pneumonia, doenças virais, cirurgias extensas.",
        "option3": "Genética e pneumonia.",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Embolia pulmonar é causada pela obstrução das artérias dos pulmões por coágulos. Fatores de risco são imobilidade prolongada, cirurgias, câncer, tabagismo, anticoncepcionais com estrógeno e reposição hormonal. Fonte: https://drauziovarella.uol.com.br/doencas-e-sintomas/embolia-pulmonar/",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 1,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Quais os alimentos corretos e frutas para diabéticos?",
        "option1": "Qualque alimento e sem controle algum.",
        "option2": "Os mesmos que os dos năo diabéticos desde que forma controlada.",
        "option3": "Só pode comer verduras e legumes.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=20",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "A dieta pra quem tem diabetes Tipo 1 é diferente de quem tem Tipo 2?",
        "option1": "Năo.",
        "option2": "Sim. Há uma contagem da quantidade de carboidrtos para adequar a quantidade de insulina baseado na quantidade de carboidrato consumido.",
        "option3": "As duas estăo erradas.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=70",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "O que comer diante de um quadro de prá-diabetes?",
        "option1": "Focar em alimentos ricos em fibras.",
        "option2": "Aumentar a quantidade de sal nos alimentos.",
        "option3": "Năo alterar a limentaçăo.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=143",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Água de coco faz mal pro diabético?",
        "option1": "Pode consumir sem restriçăo, năo faz mal algum.",
        "option2": "Pode consumir, mas com atençăo, pois tęm carboidratos.",
        "option3": "Năo deve consumir.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=226",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Comida integral(Arroz, Păo, ETC) săo liberados?",
        "option1": "Năo săo liberados, pois săo fontes de carboidratos e deve-se controlar o consumo.",
        "option2": "Săo proibidos",
        "option3": "Năo há restriçőes para alimentos integrais. Consumo liberado.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=254",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Como controlar a vontade de comer doce?",
        "option1": "Comer doces diet.",
        "option2": "Equilibrar a alimentaçăo e optar por doces mais naturais. Desde que controlado da para inserir doces na dieta.",
        "option3": "Pode comer doces a vontade.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=305",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Quais săo a pequenas opçőes de lanche para um diabético?",
        "option1": "Para os lanches intermediários: frutas secas, desidratadas e/ou oleaginosas. Para substituir o jantar: alimentos que săo fontes de vitaminas, minerais, fibras, carboidrato e proteína.",
        "option2": "Para substituir o jantar: frutas secas, desidratadas e/ou oleaginosas. Para os lanches intermediários: alimentos que săo fontes de vitaminas, minerais, fibras, carboidrato e proteína.",
        "option3": "Nenhuma das anteriores.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=382",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "O excesso de batata doce atrapalha no tratamento da diabetes?",
        "option1": "A batata doce năo atrapalha no tratamento mesmo consumida em excesso.",
        "option2": "A consumida em excesso a batata doce pode aumentar a glicose.",
        "option3": "A consumida em excesso a batata doce pode diminuir muito a glicose.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=454",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Quais os alimentos da dieta indispensáveis na manutençăo dos níveis de glicemia?",
        "option1": "Alimentos fibroso.",
        "option2": "Distribuir a alimentaçăo ao longo do dia.",
        "option3": "Todas a opçőes anteriores.",
        "correct": "3",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=509",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Qual a alimentaçăo básica para uma dieta saudável?",
        "option1": "Ter uma alimentaçăo mista: Conseguir colocar pelo menos um representante de cada grupo.",
        "option2": "Ter uma alimentaçăo vegetaria.",
        "option3": "Ter uma alimentaçăo portéica.",
        "correct": "1",
        "explanationVideo": "https://www.youtube.com/embed/-HKjqNuy6C0?start=557",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 2,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "As artérias vertebrais derivam de quais artérias?",
        "option1": "artéria axilares",
        "option2": "artérias subclávias",
        "option3": "artérias umerais",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Qual o nome da parede que separa os dois átrios?",
        "option1": "septo interatrial",
        "option2": "septo intermitral",
        "option3": "septo venoso",
        "correct":  "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question":"Qual dos ramos abaixo deriva do tronco braquiocefalico arterial?",
        "option1": "artéria subclávia esquerda",
        "option2": "artéria axilar esquerda",
        "option3": "artéria subclávia direita",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "A circulação pulmonar termina em qual cavidade?",
        "option1": "átrio direito",
        "option2": "ventrículo direito",
        "option3": "átrio esquerdo",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Nome do saco que reveste o coração?",
        "option1": "pericárdio",
        "option2": "miocárdio",
        "option3": "mesentério",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Qual vaso parte do ventrículo esquerdo?",
        "option1": "aorta",
        "option2": "veia cava superior",
        "option3": "artéria pulmonar esquerda",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Qual dos ramos abaixo deriva da artéria coronária direita?",
        "option1": "artéria circunflexa",
        "option2": "artéria marginal esquerda",
        "option3": "artéria interventricular posterior",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Qual a principal artéria medial do antebraço?",
        "option1": "artéria axilar",
        "option2": "artéria ulnar",
        "option3": "artéria braquial",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Qual dos ramos abaixo pode ser considerado o 3º ramo da porção da curva da aorta?",
        "option1": "artéria subclávia esquerda",
        "option2": "artéria subclávia direita",
        "option3": "artéria carótida comum esquerda",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "É característica de uma artéria?",
        "option1": "Levar sangue aos órgãos",
        "option2": "esticar",
        "option3": "deprimir",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Questionário de Anatomia - Sistema cardiovascular - Link: https://www.auladeanatomia.com/novosite/teste-seus-conhecimentos/questionario-sobre-sistema-cardiovascular/",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "3",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "2",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 3,
        "question": "Bla bla bla?",
        "option1": "XXX",
        "option2": "YYY",
        "option3": "ZZZ",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Fonte: Bla bla bla. Link: ",
        "explanationImage": "",
    },
    {
        "level": 4,
        "question": "Uma pessoa está com crise hipertensiva se...",
        "option1": "Sua pressão arterial está abaixo de 12x8.",
        "option2": "Sua pressçao arterial está acima de 12x8.",
        "option3": "Sua pressão arterial está acima de 12x18.",
        "correct": "2",
        "explanationVideo": "https://www.youtube.com/embed/1HDSpB_nYxs",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
    {
        "level": 5,
        "question": "Por que a insulina é importante?",
        "option1": "Diminui a quantidade de glicose nas células.",
        "option2": "Permite que a glicose entre na corrente sanguínea.",
        "option3": "Permite que a glicose entre nas células.",
        "correct": "3",
        "explanationVideo": "https://www.youtube.com/embed/vAUbt17h6Co",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "",
    },
	{
        "level": 4,
        "question": "Quando ocorre a biodisponibilidade do álcool?",
        "option1": "Quando o álcool permanece no sangue por mais tempo do que o esperado porque as células não o absorvem.",
        "option2": "Quando o álcool permanece nas células por mais tempo porque foi absorvido rápido demais.",
        "option3": "Quando o álcool fica exposto no cérebro por mais tempo porque a quantidade ingerida foi alta demais.",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "",
        "explanationImage": "alcool.jpg",
    },
    {
        "level": 5,
        "question": "Quais são as causas da embolia pulmonar?",
        "option1": "Cirurgias extensas, câncer, gravidez, obesidade e traumas.",
        "option2": "Pneumonia, doenças virais, cirurgias extensas.",
        "option3": "Genética e pneumonia.",
        "correct": "1",
        "explanationVideo": "",
        "explanationAudio": "",
        "explanationText": "Embolia pulmonar é causada pela obstrução das artérias dos pulmões por coágulos. Fatores de risco são imobilidade prolongada, cirurgias, câncer, tabagismo, anticoncepcionais com estrógeno e reposição hormonal. Fonte: https://drauziovarella.uol.com.br/doencas-e-sintomas/embolia-pulmonar/",
        "explanationImage": "",
    },
];